import { HttpStatus, ValidationPipe, type ValidationError } from '@nestjs/common';

import { AppException } from '../errors/app.exception.js';
import { ERROR_CODES } from '../errors/error-codes.js';
import type { ValidationErrorDetails } from '../errors/error-response.js';

/**
 * Flattens class-validator errors into `{ 'field.path': ['constraint', …] }`.
 *
 * The values are **constraint names**, not messages. The API owns the
 * machine-readable reason (`isEmail`, `minLength`, `isIn`), the frontend owns the
 * wording and its translation — which is what a French-first product with an
 * English locale needs. Messages generated by class-validator would arrive in
 * English and be untranslatable at the edge.
 *
 * Nested objects and arrays are flattened with dotted paths, so the frontend can
 * attach an error to the exact input: `lines.0.quantity`.
 */
export function flattenValidationErrors(
  errors: readonly ValidationError[],
  parentPath = '',
): ValidationErrorDetails {
  const flattened: ValidationErrorDetails = {};

  for (const error of errors) {
    const path = parentPath ? `${parentPath}.${error.property}` : error.property;

    if (error.constraints) {
      const constraints = Object.keys(error.constraints);
      if (constraints.length > 0) {
        flattened[path] = [...(flattened[path] ?? []), ...constraints];
      }
    }

    if (error.children && error.children.length > 0) {
      const nested = flattenValidationErrors(error.children, path);
      for (const [key, value] of Object.entries(nested)) {
        flattened[key] = [...(flattened[key] ?? []), ...value];
      }
    }
  }

  return flattened;
}

/** Turns the validator's findings into the API's error envelope. */
export function validationExceptionFactory(errors: ValidationError[]): AppException {
  return new AppException(
    HttpStatus.BAD_REQUEST,
    ERROR_CODES.VALIDATION_FAILED,
    'La requête contient des données invalides.',
    flattenValidationErrors(errors),
  );
}

/**
 * The global validation pipe.
 *
 * `whitelist` strips properties that are not declared on the DTO, and
 * `forbidNonWhitelisted` rejects the request instead of silently ignoring them —
 * an unnoticed extra field is how mass-assignment vulnerabilities start.
 * `transform` is required so that the DTO class is actually instantiated and its
 * decorators run.
 */
export function createValidationPipe(): ValidationPipe {
  return new ValidationPipe({
    whitelist: true,
    forbidNonWhitelisted: true,
    transform: true,
    exceptionFactory: validationExceptionFactory,
  });
}
